version: "3"

services:
  nginx:
    image: "nginx:latest"
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
  mysql:
    image: "mysql:latest"
    ports:
      - "33060:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/db.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "rest_db"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./db.sql:/data/application/db.sql
    networks:
      - backend
  rest.app.1:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      RESTAPI_ADDR: ":9000"
      RESTAPI_DB_NAME: "rest_db"
      RESTAPI_DB_ADDR: "mysql:3306"
      RESTAPI_DB_USERNAME: "root"
      RESTAPI_DB_PASSWORD: "root1234"
      RESTAPI_TLS_ENABLE: "false"
    ports:
      - "9001:9000"
    networks:
      - backend
    depends_on:
      - mysql
      - nginx
    links:
      - mysql
  rest.app.2:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      RESTAPI_ADDR: ":9000"
      RESTAPI_DB_NAME: "rest_db"
      RESTAPI_DB_ADDR: "mysql:3306"
      RESTAPI_DB_USERNAME: "root"
      RESTAPI_DB_PASSWORD: "root1234"
      RESTAPI_TLS_ENABLE: "false"
    ports:
      - "9002:9000"
    networks:
      - backend
    depends_on:
      - mysql
      - nginx
    links:
      - mysql

networks:
  backend:
volumes:
  data:
