mode: debug #debug/test/release
addr: :9000
name: go-rest-api
url: http://127.0.0.1:9000
secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
tls:
  enable: false
  addr: :9443
  cert: conf/server.crt
  key: conf/server.key
log:
  filePath: ./storage/log/app.log
  fileMaxSize: 10
  fileMaxAge: 32
  fileMaxBackups: 5
db:
  name: rest_api
  addr: 127.0.0.1:49155
  username: root
  password: mysqlpw
